name: Migration Workflows

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Migration action (apply one version, apply all versions, rollback one version)'
        required: true
        type: choice
        options:
          - apply_one_version
          - apply_all_versions
          - rollback_one_version

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEVELOP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY_DEVELOP }}
          passphrase: ${{ secrets.PASSPHRASE_DEVELOP }}
          script: |
            docker pull ${{ secrets.CR_REGISTRY }}/${{ secrets.CR_NAME }}-migrate:prod
            case "${{ github.event.inputs.action }}" in
            apply_one_version)
            docker-compose -f ~/space21/staging/migrations/jarvis-bot.yml --env-file ~/space21/staging/.env up -d jarvis-bot-migrate-up-one-dev
            ;;
            apply_all_versions)
            docker-compose -f ~/space21/staging/migrations/jarvis-bot.yml --env-file ~/space21/staging/.env up -d jarvis-bot-migrate-up-all-dev
            ;;
            rollback_one_version)
            docker-compose -f ~/space21/staging/migrations/jarvis-bot.yml --env-file ~/space21/staging/.env up -d jarvis-bot-migrate-down-one-dev
            ;;
            esac